// @ts-check
const childProcess = require("node:child_process")
const console = require("node:console")
const crypto = require("node:crypto")
const fs = require("node:fs/promises")
const path = require("node:path")
const process = require("node:process")
const stream = require("node:stream")
const timers = require("node:timers/promises")
const url = require("node:url")
const toml = require("@iarna/toml")
const htmlMinifier = require("html-minifier-terser")
const postcss = require("postcss")
const postcssCsso = require("postcss-csso")
const postcssImport = require("postcss-import")
const postcssMediaMinmax = require("postcss-media-minmax")
const puppeteer = require("puppeteer")

/**
 * @param config {import("@11ty/eleventy").UserConfig}
 */
module.exports = (config) => {
  config.addTemplateFormats("njk")

  config.addFilter(
    "short_date",
    /**
     * @param {string} contents
     */
    (contents) => {
      const date = new Date(contents)
      const formatter = new Intl.DateTimeFormat('en-us', {
        month: 'short',
        year: 'numeric'
      })
      return formatter.format(date)
    }
  )

  config.addFilter(
    "short_date_ru",
    /**
     * @param {string} contents
     */
    (contents) => {
      const date = new Date(contents)
      const formatter = new Intl.DateTimeFormat('ru-ru', {
        month: 'short',
        year: 'numeric'
      })
      return formatter.format(date)
    }
  )

  config.addShortcode(
    "keywords",
    /**
     * @param {string} contents
     * @param {{ verb: string[], soft: string[], hard: string[] }} keywords
     */
    (contents, keywords) => {
      let temporally = contents
      /**
       * @param {string} type
       * @param {string} keyword
       */
      function replace(type, keyword) {
        temporally = temporally.replace(
          keyword,
          `<mark class="keyword keyword_${type}">${keyword}</mark>`
        )
      }
      Object.entries(keywords).forEach(([type, keywords]) => {
        keywords.forEach((keyword) => {
          if (temporally.includes(`${keyword},`)) {
            replace(type, `${keyword},`)
            return
          }
          if (temporally.includes(`${keyword}.`)) {
            replace(type, `${keyword}.`)
            return
          }
          replace(type, keyword)
        })
      })
      return temporally
    }
  )

  config.addPairedShortcode(
    "contact",
    /**
     * @param {string} username
     * @param {string} label
     * @param {string} url
     */
    (username, label, url) => (
      ""
        + `<a href="${url}">`
        + label
        + `<span class="print-only"> (${username})</span>`
        + "</a>"
    )
  )

  config.addDataExtension(
    "toml",
    /**
     * @param {string} contents
     * @returns {any}
     */
    (contents) => toml.parse(contents)
  )

  config.addTransform(
    "minify-html",
    /**
     * @param {string} contents
     * @param {string|boolean} file
     */
    (contents, file) => (
      path.extname(String(file)) == ".html"
        ? htmlMinifier.minify(contents, {
          collapseBooleanAttributes: true,
          collapseWhitespace: true,
          decodeEntities: true,
          includeAutoGeneratedTags: false,
          removeAttributeQuotes: true,
          removeComments: true,
          removeEmptyAttributes: true,
          removeRedundantAttributes: true,
          sortAttributes: true
        })
        : Promise.resolve(contents)
    )
  )

  config.addPassthroughCopy({ "includes/{dark,light,main}.css": "." }, {
    /**
     * @param {string} input
     * @param {string} output
     */
    transform(input, output) {
      return new stream.Transform({
        transform(chunk, _, callback) {
          const contents = chunk.toString()
          // @ts-ignore
          postcss.default([
            postcssImport,
            postcssMediaMinmax,
            postcssCsso
          ])
            .process(contents, {
              from: input,
              to: output
            })
            .then((result) => {
              callback(null, result.css)
            })
            .catch((error) => {
              console.warn(error)
              callback(null, contents)
            })
        }
      })
    }
  })

  config.ignores?.add("README.md")
  config.addPassthroughCopy("LICENSE")
  config.addPassthroughCopy({ "resources": "." })
  config.setServerPassthroughCopyBehavior("copy")

  return {
    dir: {
      layouts: "includes",
      includes: "includes",
      input: ".",
      output: ".build"
    }
  }
}

/**
 * @param {string} input
 * @param {string} extension
 * @returns {Promise<string[]>}
 */
async function find(input, extension) {
  const files = []

  /**
   * @param {string} directory
   */
  async function deep(directory) {
    const dirents = await fs.readdir(directory, {
      withFileTypes: true
    })
    await Promise.all(dirents.map(async (dirent) => {
      const file = path.join(directory, dirent.name)
      if (dirent.isDirectory()) {
        await deep(file)
        return
      }
      if (!(dirent.isFile() && dirent.name.endsWith(extension))) {
        return
      }
      files.push(file)
    }))
  }

  await deep(input)
  return files
}

module.exports.hash = () => {
  new Promise(async (resolve) => {
    const sources = [
      "/dark.css",
      "/light.css",
      "/main.css",
      "/SourceCodePro-Medium.woff",
      "/SourceCodePro-Medium.woff2",
      "/WollstonecraftRomance-Regular.woff",
      "/WollstonecraftRomance-Regular.woff2"
    ]
    const map = await Promise.all(sources.map(async (source) => {
      const resolved = path.join(".build", source)
      const buffer = await fs.readFile(resolved)
      const contents = buffer.toString()
      const hash = crypto
        .createHash("md5")
        .update(contents)
        .digest("hex")
        .slice(0, 10)
      const extension = path.extname(source)
      return [source, source.replace(extension, `.${hash}${extension}`)]
    }))
    const targets = [
      path.join(".build", "main.css"),
      ...await find(".build", ".html")
    ]
    await Promise.all(targets.map(async (target) => {
      const buffer = await fs.readFile(target)
      let contents = buffer.toString()
      map.map(([raw, hashed]) => {
        contents = contents.replace(raw, hashed)
      })
      await fs.writeFile(target, contents)
    }))
    await Promise.all(map.map(async ([raw, hashed]) => {
      const resolvedRaw = path.join(".build", raw)
      const resolvedHashed = path.join(".build", hashed)
      await fs.rename(resolvedRaw, resolvedHashed)
    }))
    resolve(undefined)
  })
}

module.exports.pdf = () => {
  const serve = childProcess
    .spawn("node", [
      "node_modules/@11ty/eleventy/cmd.js",
      "--serve",
      "--dryrun"
    ])
    .on("error", (error) => {
      console.error(error)
      process.exit(1)
    })
    .on("exit", (code) => {
      if (code == 1) throw new Error("Failed to create PDF documents")
    })
  puppeteer
    .launch()
    .then(async (browser) => {
      const targets = await find(".build/cv", ".html")
      await timers.setTimeout(30000)
      await Promise.all(targets.map(async (target) => {
        const slug = target
          .replace(".build", "")
          .replace("/index.html", "")
        const url2 = new url.URL(slug, "http://localhost:8080")
        const page = await browser.newPage()
        await page.goto(url2.href, {
          waitUntil: "load"
        })
        const pdf = await page.pdf({
          displayHeaderFooter: false,
          format: "A4",
          margin: {
            top: "0",
            bottom: "0",
          },
          printBackground: true
        })
        const file = target.replace("/index.html", ".pdf")
        await fs.writeFile(file, pdf)
      }))
      await browser.close()
      serve.kill()
      process.exit(0)
    })
    .catch((error) => {
      console.error(error)
      serve.kill()
      process.exit(1)
    })
}
