noindex = true
title = "Ivan Uhalin for Laoshi · iOS Developer"
description = "iOS developer who loves what he does"
layout = "page.njk"
permalink = "cv/laoshi/index.html"

[intro]
name = "Ivan Uhalin"
position = "iOS Developer"
summary = """
I started as a frontend developer but after a few years, I switched to an apple mobile developer, wanting to build applications using native tools. I like to publish my projects in the open-source, use micro-architectures, and maintain high code requirements.
"""
postsummary = """
I'm looking for a small team in which I would be happy to work insource, entirely invest in the project and grow with it. And it looks like Laoshi is what suits me. I'm attracted by the idea to help people learn and I like the way Laoshi does it. So I hope that we will still be able to discuss cooperation.
"""

[contacts.telegram]
username = "vanyauhalin"
url = "https://t.me/vanyauhalin"

[contacts.email]
username = "vanyauhalin@gmail.com"
url = "mailto:vanyauhalin@gmail.com"

[contacts.github]
username = "vanyauhalin"
url = "https://github.com/vanyauhalin"

[contacts.linkedin]
username = "vanyauhalin"
url = "https://www.linkedin.com/in/vanyauhalin"

[contacts.site]
username = "vanyauhalin.me"
url = "https://vanyauhalin.me"

[[work]]
name = "Pochta Tech"
position = "Frontend Developer"
url = "https://pochta.tech"
start_date = "2022-03-01"
end_date = "2022-06-01"
summary = """
At the company, my team with me developed an internal application for engineers to view system messages in streaming. We worked with TypeScript and React to build UI, used GitLab, Jira, and Scrum to organize processes. At first, I spend more time communicating with the customer and PM, as well as co-mentoring the team. I was forced to leave the company due to sudden emigration.
"""

	[work.keywords]
	verb = ["developed"]
	soft = ["team", "communicating", "customer", "PM", "co-mentoring"]
	hard = ["TypeScript", "React", "GitLab", "Jira", "Scrum"]

[[work]]
name = "SK NEBO"
position = "Programmer"
start_date = "2021-02-01"
end_date = "2021-07-01"
summary = """
As a result, I single-handedly developed applications with JavaScript and Vue to automate company reporting and integrated them into CRM. During breaks, I maintained the company's business processes related to sales. I left the company to go deeper into fronted development.
"""

	[work.keywords]
	verb = ["developed", "integrated", "maintained"]
	soft = ["single-handedly"]
	hard = ["JavaScript", "Vue"]

[[work]]
name = "Freelance"
position = "Frontend Developer"
start_date = "2022-01-01"
end_date = "2022-02-01"
summary = """
I refactored two applications written with TypeScript and React to automate company reporting and merged them into one.
"""

	[work.keywords]
	verb = ["refactored", "merged"]
	soft = []
	hard = ["TypeScript", "React"]

[[work]]
name = "Freelance"
position = "Frontend Developer"
start_date = "2020-12-15"
end_date = "2021-01-31"
summary = """
Also, I developed the auto auction website for integration with CRM using vanilla tools such as JavaScript, HTML, and CSS.
"""

	[work.keywords]
	verb = ["developed"]
	soft = []
	hard = ["JavaScript", "HTML", "CSS"]

[[project]]
name = "RoutineJournal"
url = "https://github.com/vanyauhalin/RoutineJournal"
summary = """
This is an open-source application for generating mini-routine reports to better understand what my time is spent on. For the most part, the application follows the Apple calendar workflow with some features of its own. The application is built using Tuist and based on microarchitecture with an MVI pattern. SwiftUI was chosen to create the UI, and Realm to store the data.
"""

	[project.keywords]
	verb = []
	soft = ["open-source"]
	hard = ["Tuist", "microarchitecture", "MVI", "SwiftUI", "Realm"]

[[project]]
name = "dl"
url = "https://github.com/vanyauhalin/dl"
summary = """
This tool is written in Swift and also published in the open-source.
"""

	[project.keywords]
	verb = []
	soft = ["open-source"]
	hard = ["Swift"]

[[education]]
institution = "Russian New University"
url = "https://rosnou.ru"
area = "Applied Computer Science"
study_type = "Bachelor"
start_date = "2018-09-01"
end_date = "2022-07-01"
summary = """
During my studying, I understood what is conceptual, functional, and logical system design. Also learned how to analyze problem situations and develop business requirements.
"""

[skills]
skills = ["Swift", "SwiftUI", "Realm", "MongoDB", "Docker", "GitHub Actions", "Node"]
